# core_utiles/Mapper.py

# 헤더 매핑: 한글 헤더 → 영문 약어
def HMP(korean_header: str) -> str:
    HEADER_MAP = {
        "1급 정사서": "SL1",
        "2012년(A)": "12A",
        "2013년(A)": "13A",
        "2013년(B)": "13B",
        "2014년(A)": "14A",
        "2014년(B)": "14B",
        "2014년(C)": "14C",
        "2015년(A)": "15A",
        "2015년(B)": "15B",
        "2015년(C)": "15C",
        "2016년(A)": "16A",
        "2016년(B)": "16B",
        "2016년(C)": "16C",
        "2017년(A)": "17A",
        "2017년(B)": "17B",
        "2017년(C)": "17C",
        "2018년(A)": "18A",
        "2018년(B)": "18B",
        "2018년(C)": "18C",
        "2019년(A)": "19A",
        "2019년(B)": "19B",
        "2019년(C)": "19C",
        "2020년(A)": "20A",
        "2020년(B)": "20B",
        "2020년(C)": "20C",
        "2021년(A)": "21A",
        "2021년(B)": "21B",
        "2021년(C)": "21C",
        "2022년(A)": "22A",
        "2022년(B)": "22B",
        "2022년(C)": "22C",
        "2023년(B)": "23B",
        "2023년(C)": "23C",
        "2024년(C)": "24C",
        "2급 정사서": "SL2",
        "[구독] e-Book": "EB",
        "[구독] e-book": "EB",
        "결산": "STL",
        "겸직": "MRL",
        "계": "SUM",
        "교원": "FAC",
        "교육 참가자수": "EP",
        "교육 참여시간": "EH",
        "교육횟수": "EDC",
        "구입": "BUY",
        "국내": "KR",
        "국내서": "KB",
        "국외": "OT",
        "국외서": "OB",
        "기증": "DON",
        "기타": "OTH",
        "기타 전자자료": "OER",
        "당해년도": "CYR",
        "대면 이용자 교육": "OEU",
        "대면교육": "OE",
        "대출자수": "LU",
        "대출책수": "LB",
        "대출현황": "LS",
        "대학규모": "USC",
        "대학원생": "GRAD",
        "대학총결산": "USTL",
        "대학총결산 대비 도서관 자료구입비 비율": "LBRT",
        "대학총결산 대비 자료구입비 비율": "BRT",
        "대학총예산": "UBGT",
        "도서관 이용자수": "LUC",
        "도서관건물연면적": "LA",
        "도서관건물연면적 (제곱미터)": "LAS",
        "도서관직원수 비정규직": "LPT",
        "도서관직원수 정규직": "LFT",
        "도서자료": "BR",
        "도서자료 구입비": "BC",
        "동영상강의자료(e-Learning)": "ELV",
        "면담": "CSLT",
        "미소지자": "NOH",
        "방문자수": "VC",
        "번호": "ID",
        "봉사대상자수": "VTC",
        "봉사대상자수 및 이용자수": "VUC",
        "비대면 실시간 교육": "REL",
        "비대면 이용자 교육": "REU",
        "비도서자료 구입비": "NBC",
        "비사서": "NLIB",
        "비전임교원": "PFAC",
        "비정규직": "PT",
        "사서": "LIB",
        "사서자격증 미소지자": "NLIBC",
        "사서자격증 보유현황": "LIBCS",
        "사서자격증 소지자": "HLIBC",
        "사서직원수 비정규직": "LPT2",
        "사서직원수 정규직": "LFT2",
        "상호대차 신청 및 제공 건수": "RFLN",
        "설립": "FND",
        "설비": "EQP",
        "소장도서수": "BO",
        "순위": "RK",
        "시설": "FACLT",
        "신청": "REQ",
        "업무용컴퓨터(PC)수": "SPC",
        "연간 장서 증가 및 폐기 책수": "AHC",
        "연간 장서 증가 종수": "ATI",
        "연간 장서 증가 책수": "ABI",
        "연간 장서 폐기 책수": "ARM",
        "연간장서증가율": "GRR",
        "연간장서증가책수": "AHBC",
        "연도": "YR",
        "연면적": "AR",
        "연속간행물": "SRL",
        "연속간행물 구입비": "SRC",
        "열람석": "RS",
        "예산": "BGT",
        "예측": "EST",
        "온라인": "ONL",
        "온라인 교육": "OE2",
        "원문복사 신청 및 제공 건수": "RFC",
        "웹DB": "WDB",
        "이용자 교육": "UE",
        "이용자수": "UC",
        "이용자용컴퓨터(PC)수": "UPC",
        "자료구입비": "MC",
        "자료구입비(결산)": "MCS",
        "자료구입비계": "MCT",
        "재학생 1,000명당 도서관 직원수": "SPK",
        "재학생 1,000명당 사서 직원수": "LPK",
        "재학생 1인당 도서관건물 연면적": "APS",
        "재학생 1인당 도서관방문자수": "VPS",
        "재학생 1인당 대출책수": "LPS",
        "재학생 1인당 소장도서수": "BPS",
        "재학생 1인당 자료구입비": "CPS",
        "재학생 1인당 자료구입비(결산)": "CPSS",
        "재학생수": "SC",
        "재학생수(당해년도)": "SCC",
        "재학생수(전년도)": "SCP",
        "전년도": "PYR",
        "전담": "EXC",
        "전임교원": "FFAC",
        "전자자료": "ER",
        "전자자료 구입비": "ERC",
        "전자저널": "EJN",
        "전화": "PHN",
        "점수": "SCR",
        "정규직": "FT",
        "정보화기기(PC)수": "TPC",
        "제공": "PRV",
        "종수": "TCNT",
        "준사서": "ALIB",
        "지역": "RGN",
        "직원": "STF",
        "직원 1인당 평균 교육 참여 시간": "EHS",
        "직원교육현황": "SES",
        "참고서비스 및 상호협력": "RCOL",
        "참고서비스 신청 및 제공 건수 (2010년 이전)": "RBF10",
        "참고서비스 제공 건수 (2010년 이후)": "RAF10",
        "참여시간": "PTH",
        "참여인원": "PTC",
        "책수": "BCNT",
        "총 보유컴퓨터(PC)수": "TPC",
        "총열람석수": "TRS",
        "최근 3년간 자료구입비 증가율(결산)": "BG3Y",
        "패키지": "PKG",
        "학과수": "DPC",
        "학교명": "SNM",
        "학교유형": "STYP",
        "학부생": "UGRD",
        "합계": "TTL"
    }
    return HEADER_MAP.get(korean_header, korean_header)

# 대학명 매핑: 영문 대학명 → 한글 대학명
def NMP(english_name: str) -> str:
    NAME_MAP = {
        "Ajou University": "아주대학교",
        "Catholic Kwandong University": "가톨릭관동대학교",
        "Catholic University of Daegu": "대구가톨릭대학교",
        "Catholic University of Korea": "가톨릭대학교",
        "Cha University": "차의과학대학교",
        "Chonbuk National University": "전북대학교",
        "Chonnam National University": "전남대학교",
        "Chosun University": "조선대학교",
        "Chung-Ang University": "중앙대학교",
        "Chungbuk National University": "충북대학교",
        "Chungnam National University": "충남대학교",
        "Daegu Gyeongbuk Institute of Science and Technology": "대구경북과학기술원",
        "Daegu University": "대구대학교",
        "Dankook University": "단국대학교",
        "Dong-A University": "동아대학교",
        "Dongguk University": "동국대학교",
        "Eulji University": "을지대학교",
        "Ewha Womans University": "이화여자대학교",
        "Gachon University": "가천대학교",
        "Gangneung-Wonju National University": "국립강릉원주대학교",
        "Gwangju Institute of Science and Technology": "광주과학기술원",
        "Gyeongsang National University": "경상국립대학교",
        "Hallym University": "한림대학교",
        "Hanbat National University": "국립한밭대학교",
        "Hankuk University of Foreign Studies": "한국외국어대학교",
        "Hanyang University": "한양대학교",
        "Hongik University": "홍익대학교",
        "Incheon National University": "인천대학교",
        "Inha University": "인하대학교",
        "Inje University": "인제대학교",
        "Jeju National University": "제주대학교",
        "Jeonbuk National University": "전북대학교",
        "KAIST": "한국과학기술원",
        "Kangwon National University": "강원대학교",
        "Keimyung University": "계명대학교",
        "Kongju National University": "국립공주대학교",
        "Konkuk University": "건국대학교",
        "Kookmin University": "국민대학교",
        "Korea Advanced Institute of Science and Technology (KAIST)": "한국과학기술원",
        "Korea University": "고려대학교",
        "Kosin University": "고신대학교",
        "Kunsan National University": "국립군산대학교",
        "Kwangwoon University": "광운대학교",
        "Kyonggi University": "경기대학교",
        "Kyung Hee University": "경희대학교",
        "Kyungpook National University": "경북대학교",
        "Myongji University": "명지대학교",
        "Pohang University of Science and Technology": "포항공과대학교",
        "Pukyong National University": "국립부경대학교",
        "Pusan National University": "부산대학교",
        "Sejong University": "세종대학교",
        "Seoul National University": "서울대학교",
        "Seoul National University of Science and Technology": "서울과학기술대학교",
        "Sogang University": "서강대학교",
        "Sookmyung Women's University": "숙명여자대학교",
        "Soonchunhyang University": "순천향대학교",
        "Soongsil University": "숭실대학교",
        "Sunchon National University": "국립순천대학교",
        "Sungkyunkwan University": "성균관대학교",
        "Ulsan National Institute of Science and Technology": "울산과학기술원",
        "University of Science and Technology, Korea": "과학기술연합대학원대학교",
        "University of Seoul": "서울시립대학교",
        "University of Ulsan": "울산대학교",
        "Wonkwang University": "원광대학교",
        "Yeungnam University": "영남대학교",
        "Yonsei University": "연세대학교"
    }
    return NAME_MAP.get(english_name, english_name)

def HMP_R(english_header: str) -> str:
    HEADER_MAP_REVERS = {
        "SL1": "1급 정사서",
        "12A": "2012년(A)",
        "13A": "2013년(A)",
        "13B": "2013년(B)",
        "14A": "2014년(A)",
        "14B": "2014년(B)",
        "14C": "2014년(C)",
        "15A": "2015년(A)",
        "15B": "2015년(B)",
        "15C": "2015년(C)",
        "16A": "2016년(A)",
        "16B": "2016년(B)",
        "16C": "2016년(C)",
        "17A": "2017년(A)",
        "17B": "2017년(B)",
        "17C": "2017년(C)",
        "18A": "2018년(A)",
        "18B": "2018년(B)",
        "18C": "2018년(C)",
        "19A": "2019년(A)",
        "19B": "2019년(B)",
        "19C": "2019년(C)",
        "20A": "2020년(A)",
        "20B": "2020년(B)",
        "20C": "2020년(C)",
        "21A": "2021년(A)",
        "21B": "2021년(B)",
        "21C": "2021년(C)",
        "22A": "2022년(A)",
        "22B": "2022년(B)",
        "22C": "2022년(C)",
        "23B": "2023년(B)",
        "23C": "2023년(C)",
        "24C": "2024년(C)",
        "SL2": "2급 정사서",
        "EB": "[구독] e-book",
        "STL": "결산",
        "MRL": "겸직",
        "SUM": "계",
        "FAC": "교원",
        "EP": "교육 참가자수",
        "EH": "교육 참여시간",
        "EDC": "교육횟수",
        "BUY": "구입",
        "KR": "국내",
        "KB": "국내서",
        "OT": "국외",
        "OB": "국외서",
        "DON": "기증",
        "OTH": "기타",
        "OER": "기타 전자자료",
        "CYR": "당해년도",
        "OEU": "대면 이용자 교육",
        "OE": "대면교육",
        "LU": "대출자수",
        "LB": "대출책수",
        "LS": "대출현황",
        "USC": "대학규모",
        "GRAD": "대학원생",
        "USTL": "대학총결산",
        "LBRT": "대학총결산 대비 도서관 자료구입비 비율",
        "BRT": "대학총결산 대비 자료구입비 비율",
        "UBGT": "대학총예산",
        "LUC": "도서관 이용자수",
        "LA": "도서관건물연면적",
        "LAS": "도서관건물연면적 (제곱미터)",
        "LPT": "도서관직원수 비정규직",
        "LFT": "도서관직원수 정규직",
        "BR": "도서자료",
        "BC": "도서자료 구입비",
        "ELV": "동영상강의자료(e-Learning)",
        "CSLT": "면담",
        "NOH": "미소지자",
        "VC": "방문자수",
        "ID": "번호",
        "VTC": "봉사대상자수",
        "VUC": "봉사대상자수 및 이용자수",
        "REL": "비대면 실시간 교육",
        "REU": "비대면 이용자 교육",
        "NBC": "비도서자료 구입비",
        "NLIB": "비사서",
        "PFAC": "비전임교원",
        "PT": "비정규직",
        "LIB": "사서",
        "NLIBC": "사서자격증 미소지자",
        "LIBCS": "사서자격증 보유현황",
        "HLIBC": "사서자격증 소지자",
        "LPT2": "사서직원수 비정규직",
        "LFT2": "사서직원수 정규직",
        "RFLN": "상호대차 신청 및 제공 건수",
        "FND": "설립",
        "EQP": "설비",
        "BO": "소장도서수",
        "RK": "순위",
        "FACLT": "시설",
        "REQ": "신청",
        "SPC": "업무용컴퓨터(PC)수",
        "AHC": "연간 장서 증가 및 폐기 책수",
        "ATI": "연간 장서 증가 종수",
        "ABI": "연간 장서 증가 책수",
        "ARM": "연간 장서 폐기 책수",
        "GRR": "연간장서증가율",
        "AHBC": "연간장서증가책수",
        "YR": "연도",
        "AR": "연면적",
        "SRL": "연속간행물",
        "SRC": "연속간행물 구입비",
        "RS": "열람석",
        "BGT": "예산",
        "EST": "예측",
        "ONL": "온라인",
        "OE2": "온라인 교육",
        "RFC": "원문복사 신청 및 제공 건수",
        "WDB": "웹DB",
        "UE": "이용자 교육",
        "UC": "이용자수",
        "UPC": "이용자용컴퓨터(PC)수",
        "MC": "자료구입비",
        "MCS": "자료구입비(결산)",
        "MCT": "자료구입비계",
        "SPK": "재학생 1,000명당 도서관 직원수",
        "LPK": "재학생 1,000명당 사서 직원수",
        "APS": "재학생 1인당 도서관건물 연면적",
        "VPS": "재학생 1인당 도서관방문자수",
        "LPS": "재학생 1인당 대출책수",
        "BPS": "재학생 1인당 소장도서수",
        "CPS": "재학생 1인당 자료구입비",
        "CPSS": "재학생 1인당 자료구입비(결산)",
        "SC": "재학생수",
        "SCC": "재학생수(당해년도)",
        "SCP": "재학생수(전년도)",
        "PYR": "전년도",
        "EXC": "전담",
        "FFAC": "전임교원",
        "ER": "전자자료",
        "ERC": "전자자료 구입비",
        "EJN": "전자저널",
        "PHN": "전화",
        "SCR": "점수",
        "FT": "정규직",
        "TPC": "총 보유컴퓨터(PC)수",
        "PRV": "제공",
        "TCNT": "종수",
        "ALIB": "준사서",
        "RGN": "지역",
        "STF": "직원",
        "EHS": "직원 1인당 평균 교육 참여 시간",
        "SES": "직원교육현황",
        "RCOL": "참고서비스 및 상호협력",
        "RBF10": "참고서비스 신청 및 제공 건수 (2010년 이전)",
        "RAF10": "참고서비스 제공 건수 (2010년 이후)",
        "PTH": "참여시간",
        "PTC": "참여인원",
        "BCNT": "책수",
        "TRS": "총열람석수",
        "BG3Y": "최근 3년간 자료구입비 증가율(결산)",
        "PKG": "패키지",
        "DPC": "학과수",
        "SNM": "학교명",
        "STYP": "학교유형",
        "UGRD": "학부생",
        "TTL": "합계"
    }
    return HEADER_MAP_REVERS.get(english_header, english_header)
